# Generated by Django 4.2.25 on 2026-01-04 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_remove_bus_direction'),
        ('routes', '0002_alter_route_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='buses',
            field=models.ManyToManyField(related_name='routes', to='buses.bus'),
        ),
        migrations.AlterField(
            model_name='route',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_routes', to='buses.bus'),
        ),
    ]
