# Generated by Django 4.2.25 on 2026-01-04 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_remove_bus_direction'),
        ('routes', '0003_route_buses_alter_route_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='buses',
        ),
        migrations.AlterField(
            model_name='route',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buses.bus'),
        ),
    ]
