# Generated by Django 4.2.25 on 2026-01-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_remove_route_buses_alter_route_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='bus',
        ),
    ]
