# Generated by Django 4.2.25 on 2026-01-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_bus_direction_alter_bus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='direction',
        ),
    ]
