# Generated by Django 4.2.7 on 2026-01-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0002_alter_stop_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['route', 'order'], 'verbose_name': 'Stop', 'verbose_name_plural': 'Stops'},
        ),
    ]
