# Generated by Django 6.0 on 2025-12-23 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livelocation',
            options={'verbose_name': 'Live Location', 'verbose_name_plural': 'Live Locations'},
        ),
        migrations.AddField(
            model_name='livelocation',
            name='current_stop_index',
            field=models.IntegerField(default=0, help_text='Index of the current stop in the route'),
        ),
        migrations.AlterField(
            model_name='livelocation',
            name='bus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to='buses.bus'),
        ),
        migrations.AlterField(
            model_name='livelocation',
            name='latitude',
            field=models.FloatField(help_text='Current latitude of the bus'),
        ),
        migrations.AlterField(
            model_name='livelocation',
            name='longitude',
            field=models.FloatField(help_text='Current longitude of the bus'),
        ),
        migrations.AlterField(
            model_name='livelocation',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, help_text='Last updated time'),
        ),
    ]
