# Generated by Django 4.2.25 on 2026-01-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_livelocation_last_moved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='livelocation',
            name='is_moving_forward',
            field=models.BooleanField(default=True, help_text='True = Start to End, False = End to Start'),
        ),
    ]
