# Generated by Django 4.2.7 on 2026-01-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_livelocation_is_moving_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='livelocation',
            name='stop_arrival_time',
            field=models.DateTimeField(blank=True, help_text='Time when bus arrived at current stop (for 2-second delay)', null=True),
        ),
        migrations.AlterField(
            model_name='livelocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
