# Generated by Django 4.2.7 on 2026-01-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_livelocation_stop_arrival_time_alter_livelocation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='livelocation',
            name='crowding',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', help_text='Current crowding level', max_length=10),
        ),
        migrations.AddField(
            model_name='livelocation',
            name='speed',
            field=models.IntegerField(default=40, help_text='Current speed in km/h'),
        ),
    ]
